port=53
listen-address=127.0.0.1,192.168.50.5
bind-interfaces

no-resolv
server=192.168.50.1
server=1.1.1.1

domain-needed
bogus-priv
cache-size=1000
local-ttl=300

address=/imtegrale.example-tailnet.ts.net/192.168.50.5
