from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import sys
import zipfile
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "scripts"


def _load_scanner() -> ModuleType:
    if str(SCRIPTS) not in sys.path:
        sys.path.insert(0, str(SCRIPTS))
    path = SCRIPTS / "check_secrets.py"
    spec = importlib.util.spec_from_file_location("c6c_policy_scanner", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def scanner() -> ModuleType:
    return _load_scanner()


def _binary_entry(data: bytes, paths: list[str]) -> dict[str, object]:
    return {
        "allowed_paths": sorted(paths),
        "logical_type": "katex_font_woff",
        "media_type": "font/woff",
        "policy": "immutable_vendor_asset",
        "provenance": "Synthetic C6C digest policy test fixture.",
        "purpose": "immutable_vendor_asset",
        "review": "No production or student data; exact bytes generated by the test.",
        "scopes": ["repository"],
        "sha256": hashlib.sha256(data).hexdigest(),
        "size": len(data),
    }


def _write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _empty_exemptions(tmp_path: Path) -> Path:
    path = tmp_path / "exemptions.json"
    _write_json(path, {"exemptions": [], "schema_version": 1})
    return path


def _empty_binaries(tmp_path: Path) -> Path:
    path = tmp_path / "binaries.json"
    _write_json(path, {"entries": [], "schema_version": 1})
    return path


def _scan_repository_policy(
    scanner: ModuleType,
    paths: list[Path],
    root: Path,
    binary_manifest: Path,
    exemptions_manifest: Path,
    *,
    enforce_unused: bool = True,
):  # noqa: ANN202
    return scanner.scan_paths_report(
        paths,
        root=root,
        policy_scope="repository",
        enforce_unused=enforce_unused,
        binary_allowlist_path=binary_manifest,
        secret_exemptions_path=exemptions_manifest,
    )


def test_exact_binary_digest_size_and_path_are_required(
    tmp_path: Path,
    scanner: ModuleType,
) -> None:
    payload = b"wOFF" + b"\x00" * 128
    source = tmp_path / "vendor.woff"
    source.write_bytes(payload)
    manifest = tmp_path / "binary.json"
    _write_json(manifest, {"entries": [_binary_entry(payload, [source.name])], "schema_version": 1})

    report = _scan_repository_policy(
        scanner,
        [source],
        tmp_path,
        manifest,
        _empty_exemptions(tmp_path),
    )

    assert report.ok
    assert report.binary_files_seen == 1
    assert report.binary_files_digest_allowlisted == 1
    assert report.binary_bytes_covered == len(payload)
    assert report.binary_regions_unscanned == 0
    assert report.unused_binary_allowlist_entries == 0


@pytest.mark.parametrize("mutation", ["one_byte", "size", "trailing"])
def test_any_binary_byte_or_size_change_is_rejected(
    tmp_path: Path,
    scanner: ModuleType,
    mutation: str,
) -> None:
    original = b"wOFF" + b"\x00" * 128
    source = tmp_path / "vendor.woff"
    changed = bytearray(original)
    if mutation == "one_byte":
        changed[-1] ^= 1
    elif mutation == "size":
        changed = changed[:-1]
    else:
        changed.extend(b"polyglot-trailer")
    source.write_bytes(changed)
    manifest = tmp_path / "binary.json"
    _write_json(manifest, {"entries": [_binary_entry(original, [source.name])], "schema_version": 1})

    report = _scan_repository_policy(
        scanner,
        [source],
        tmp_path,
        manifest,
        _empty_exemptions(tmp_path),
    )

    assert not report.ok
    assert report.binary_files_rejected == 1
    assert report.binary_files_digest_allowlisted == 0
    assert report.binary_regions_unscanned == 0


@pytest.mark.parametrize(
    "payload",
    [
        b"wOFF" + b"\x00" * 32,
        b"not-a-font-with-a-woff-extension",
        b"\x00\xffunknown-binary",
        b"wOFF" + b"PK\x03\x04" + b"\x00" * 32,
    ],
)
def test_magic_extension_invalid_format_and_polyglot_never_authorize(
    tmp_path: Path,
    scanner: ModuleType,
    payload: bytes,
) -> None:
    source = tmp_path / "unlisted.woff"
    source.write_bytes(payload)

    report = scanner.scan_paths_report([source], root=tmp_path)

    assert report.binary_files_rejected == 1
    assert report.binary_files_digest_allowlisted == 0


def test_digest_at_wrong_path_and_unused_entry_fail_closed(
    tmp_path: Path,
    scanner: ModuleType,
) -> None:
    payload = b"wOFF" + b"\x00" * 64
    allowed = "allowed.woff"
    wrong = tmp_path / "wrong.woff"
    wrong.write_bytes(payload)
    manifest = tmp_path / "binary.json"
    _write_json(manifest, {"entries": [_binary_entry(payload, [allowed])], "schema_version": 1})

    report = _scan_repository_policy(
        scanner,
        [wrong],
        tmp_path,
        manifest,
        _empty_exemptions(tmp_path),
    )

    assert not report.ok
    assert report.binary_files_rejected == 1
    assert report.unused_binary_allowlist_entries == 1


def test_one_digest_can_bind_exact_source_and_build_paths(
    tmp_path: Path,
    scanner: ModuleType,
) -> None:
    payload = b"wOFF" + b"\x00" * 96
    source = tmp_path / "source.woff"
    built = tmp_path / "build.woff"
    source.write_bytes(payload)
    built.write_bytes(payload)
    manifest = tmp_path / "binary.json"
    _write_json(
        manifest,
        {
            "entries": [_binary_entry(payload, [built.name, source.name])],
            "schema_version": 1,
        },
    )

    report = _scan_repository_policy(
        scanner,
        [source, built],
        tmp_path,
        manifest,
        _empty_exemptions(tmp_path),
    )

    assert report.ok
    assert report.binary_files_digest_allowlisted == 2


@pytest.mark.parametrize("invalid", ["wildcard", "duplicate", "extra_field", "bad_sha"])
def test_binary_allowlist_schema_is_strict(
    tmp_path: Path,
    scanner: ModuleType,
    invalid: str,
) -> None:
    payload = b"wOFF" + b"\x00" * 32
    entry = _binary_entry(payload, ["vendor.woff"])
    entries = [entry]
    if invalid == "wildcard":
        entry["allowed_paths"] = ["*.woff"]
    elif invalid == "duplicate":
        entries = [entry, dict(entry)]
    elif invalid == "extra_field":
        entry["unexpected"] = True
    else:
        entry["sha256"] = "A" * 64
    manifest = tmp_path / "invalid-binary.json"
    _write_json(manifest, {"entries": entries, "schema_version": 1})

    report = _scan_repository_policy(
        scanner,
        [],
        tmp_path,
        manifest,
        _empty_exemptions(tmp_path),
    )

    assert not report.ok
    assert report.findings[0][2].startswith(("BINARY_", "POLICY_"))


def _telegram_value(fill: str = "A") -> bytes:
    return ("123456:" + fill * 24).encode("ascii")


def _exemption(value: bytes, *, path: str, maximum: int = 1) -> dict[str, object]:
    return {
        "max_occurrences": maximum,
        "path": path,
        "purpose": "synthetic_detector_fixture",
        "rule_id": "TELEGRAM_TOKEN",
        "value_sha256": hashlib.sha256(value).hexdigest(),
    }


def test_exact_telegram_value_rule_path_and_occurrence_are_exempted(
    tmp_path: Path,
    scanner: ModuleType,
) -> None:
    relative = "backend/tests/fixture.py"
    source = tmp_path / relative
    source.parent.mkdir(parents=True)
    value = _telegram_value()
    source.write_bytes(b"TOKEN = b'" + value + b"'\n")
    exemptions = tmp_path / "exemptions.json"
    _write_json(
        exemptions,
        {"exemptions": [_exemption(value, path=relative)], "schema_version": 1},
    )

    report = _scan_repository_policy(
        scanner,
        [source],
        tmp_path,
        _empty_binaries(tmp_path),
        exemptions,
    )

    assert report.ok
    assert report.exemptions_applied == 1
    assert report.exemptions_rejected == 0
    assert report.unused_secret_exemptions == 0


def test_unused_secret_exemption_fails_closed(
    tmp_path: Path,
    scanner: ModuleType,
) -> None:
    source = tmp_path / "backend/tests/fixture.py"
    source.parent.mkdir(parents=True)
    source.write_text("# clean synthetic fixture\n", encoding="utf-8")
    exemptions = tmp_path / "exemptions.json"
    _write_json(
        exemptions,
        {
            "exemptions": [
                _exemption(_telegram_value(), path="backend/tests/fixture.py")
            ],
            "schema_version": 1,
        },
    )

    report = _scan_repository_policy(
        scanner,
        [source],
        tmp_path,
        _empty_binaries(tmp_path),
        exemptions,
    )

    assert not report.ok
    assert report.unused_secret_exemptions == 1
    assert ("secret-policy", 0, "SECRET_EXEMPTION_UNUSED") in report.findings


@pytest.mark.parametrize("variant", ["wrong_path", "wrong_value", "same_context", "too_many"])
def test_telegram_exemption_cannot_suppress_neighboring_values_or_contexts(
    tmp_path: Path,
    scanner: ModuleType,
    variant: str,
) -> None:
    relative = "backend/tests/fixture.py"
    exempt = _telegram_value("A")
    observed = exempt
    source_relative = relative
    maximum = 1
    if variant == "wrong_path":
        source_relative = "backend/tests/other_fixture.py"
    elif variant in {"wrong_value", "same_context"}:
        observed = _telegram_value("Z")
    source = tmp_path / source_relative
    source.parent.mkdir(parents=True, exist_ok=True)
    prefix = b"# synthetic fictional fixture on the same line " if variant == "same_context" else b""
    occurrences = 2 if variant == "too_many" else 1
    source.write_bytes(prefix + b" ".join([observed] * occurrences) + b"\n")
    exemptions = tmp_path / "exemptions.json"
    _write_json(
        exemptions,
        {
            "exemptions": [_exemption(exempt, path=relative, maximum=maximum)],
            "schema_version": 1,
        },
    )

    report = _scan_repository_policy(
        scanner,
        [source],
        tmp_path,
        _empty_binaries(tmp_path),
        exemptions,
    )

    assert not report.ok
    assert "TELEGRAM_TOKEN" in {rule for _, _, rule in report.findings}
    assert observed.decode("ascii") not in repr(report.findings)


def test_archive_member_cannot_inherit_repository_fixture_exemption(
    tmp_path: Path,
    scanner: ModuleType,
) -> None:
    relative = "backend/tests/fixture.py"
    value = _telegram_value()
    archive_path = tmp_path / "fixture.zip"
    with zipfile.ZipFile(archive_path, "w") as archive:
        archive.writestr(relative, value)
    exemptions = tmp_path / "exemptions.json"
    _write_json(
        exemptions,
        {"exemptions": [_exemption(value, path=relative)], "schema_version": 1},
    )

    report = _scan_repository_policy(
        scanner,
        [archive_path],
        tmp_path,
        _empty_binaries(tmp_path),
        exemptions,
    )

    assert not report.ok
    assert report.exemptions_applied == 0
    assert "TELEGRAM_TOKEN" in {rule for _, _, rule in report.findings}


@pytest.mark.parametrize(
    "mutation",
    ["wildcard", "traversal", "invalid_sha", "extra_field", "production", "duplicate"],
)
def test_secret_exemption_manifest_rejects_broad_or_stale_shapes(
    tmp_path: Path,
    scanner: ModuleType,
    mutation: str,
) -> None:
    value = _telegram_value()
    entry = _exemption(value, path="backend/tests/fixture.py")
    entries = [entry]
    if mutation == "wildcard":
        entry["path"] = "backend/tests/*.py"
    elif mutation == "traversal":
        entry["path"] = "backend/tests/../fixture.py"
    elif mutation == "invalid_sha":
        entry["value_sha256"] = "0" * 63
    elif mutation == "extra_field":
        entry["context"] = "synthetic"
    elif mutation == "production":
        entry["path"] = "backend/app/config.py"
    else:
        entries = [entry, dict(entry)]
    exemptions = tmp_path / "invalid-exemptions.json"
    _write_json(exemptions, {"exemptions": entries, "schema_version": 1})

    report = _scan_repository_policy(
        scanner,
        [],
        tmp_path,
        _empty_binaries(tmp_path),
        exemptions,
    )

    assert not report.ok
    assert report.findings[0][2].startswith(("SECRET_", "POLICY_"))


def test_symlink_and_hardlink_never_reuse_binary_authorization(
    tmp_path: Path,
    scanner: ModuleType,
) -> None:
    payload = b"wOFF" + b"\x00" * 48
    original = tmp_path / "original.woff"
    original.write_bytes(payload)
    symlink = tmp_path / "symlink.woff"
    symlink.symlink_to(original)
    hardlink = tmp_path / "hardlink.woff"
    os.link(original, hardlink)
    manifest = tmp_path / "binary.json"
    _write_json(
        manifest,
        {
            "entries": [_binary_entry(payload, [hardlink.name, original.name, symlink.name])],
            "schema_version": 1,
        },
    )

    report = _scan_repository_policy(
        scanner,
        [symlink, hardlink],
        tmp_path,
        manifest,
        _empty_exemptions(tmp_path),
        enforce_unused=False,
    )

    assert not report.ok
    assert {rule for _, _, rule in report.findings} == {"HARDLINK_REJECTED", "SYMLINK_REJECTED"}
