[Journal]
Storage=persistent
Compress=yes
Seal=yes
SystemMaxUse=512M
SystemKeepFree=2G
SystemMaxFileSize=64M
RuntimeMaxUse=128M
MaxFileSec=1week
MaxRetentionSec=1month
RateLimitIntervalSec=30s
RateLimitBurst=10000
