# These uncommon protocol families are not used by this single-node PVE.
install dccp /bin/false
install rds /bin/false
install sctp /bin/false
install tipc /bin/false

blacklist dccp
blacklist rds
blacklist sctp
blacklist tipc
