"""Stable wire and persistence bounds for encrypted PASS/HUB service sessions."""

PASS_SERVICE_SESSION_MAX_BYTES = 64 * 1_024
PASS_SERVICE_SESSION_FRAME_HEADER_BYTES = 14
PASS_SERVICE_SESSION_MIN_PADDING_BYTES = 2
PASS_SERVICE_SESSION_FRAME_SIZE = (
    PASS_SERVICE_SESSION_MAX_BYTES
    + PASS_SERVICE_SESSION_FRAME_HEADER_BYTES
    + PASS_SERVICE_SESSION_MIN_PADDING_BYTES
)
PASS_SERVICE_SESSION_HPKE_OVERHEAD_BYTES = 48
PASS_SERVICE_SESSION_ENVELOPE_HEADER_BYTES = 52
PASS_SERVICE_SESSION_ENVELOPE_BYTES = (
    PASS_SERVICE_SESSION_FRAME_SIZE
    + PASS_SERVICE_SESSION_HPKE_OVERHEAD_BYTES
    + PASS_SERVICE_SESSION_ENVELOPE_HEADER_BYTES
)
